### ISSUE TITLE
--ddcloud-networkdomain needs to be url encoded

### ISSUE THREAD

**Issue by adrianvolpe** [DimensionDataResearch/docker-machine-driver-ddcloud#2]
When trying this driver I ran into an issue where I got the following error:
<pre>Development' in region 'EU'...
Error with pre-create check: "Unexpected error while performing 'GET' request to 'https://api-EU.dimensiondata.com/caas/2.2/9ce4f241-ae0f-47c2-a042-7e285b9875b7/network/networkDomain?name=Enterprise message routing (EMR) Development&datacenterId=EU7': Get https://api-EU.dimensiondata.com/caas/2.2/9ce4f241-ae0f-47c2-a042-7e285b9875b7/network/networkDomain?name=Enterprise message routing (EMR) Development&datacenterId=EU7: read tcp 10.1.1.13:51291->83.217.252.132:443: read: connection reset by peer"</pre>

I did a bit of investigating and it turns out that the network name I have: **Enterprise message routing (EMR) Development** if not passed to docker-machine as a url encoded value will not work.

If you could do the url encoding in the driver that would be awesome.

The following is the original request I made that did not work (excluding my username and password):
<pre>$docker-machine create --driver ddcloud \
--ddcloud-region EU \
--ddcloud-datacenter EU7 \
--ddcloud-networkdomain "Enterprise message routing (EMR) Development" \
--ddcloud-vlan 'Development' \
--ddcloud-ssh-key ~/.ssh/id_rsa.uat-gsoaapp \
--ddcloud-ssh-bootstrap-password 'throw-away-password' \
--ddcloud-user 'xxxxxxx' \
--ddcloud-password 'xxxxx'\
 devdock01

Running pre-create checks…
(devdock01) Will create machine 'devdock01' on VLAN 'Development' in network domain 'Enterprise message routing (EMR) Development' (data centre 'EU7').
(devdock01) Resolving target network domain 'Enterprise message routing (EMR) Development' in region 'EU'...
Error with pre-create check: "Unexpected error while performing 'GET' request to 'https://api-EU.dimensiondata.com/caas/2.2/9ce4f241-ae0f-47c2-a042-7e285b9875b7/network/networkDomain?name=Enterprise message routing (EMR) Development&datacenterId=EU7': Get https://api-EU.dimensiondata.com/caas/2.2/9ce4f241-ae0f-47c2-a042-7e285b9875b7/network/networkDomain?name=Enterprise message routing (EMR) Development&datacenterId=EU7: read tcp 10.1.1.13:51291->83.217.252.132:443: read: connection reset by peer"</pre>

This is the version that worked even though it reports an error:

<pre>$docker-machine create --driver ddcloud \
--ddcloud-region EU \
--ddcloud-datacenter EU7 \
--ddcloud-networkdomain 'Enterprise%20message%20routing%20(EMR)%20Development' \
--ddcloud-vlan Development \
--ddcloud-ssh-key ~/.ssh/id_rsa.uat-gsoaapp \
--ddcloud-ssh-bootstrap-password 'throw-away-password' \
--ddcloud-user 'xxx' --ddcloud-password 'xxxx' devdock01

Running pre-create checks...
(devdock01) Will create machine 'devdock01' on VLAN 'Development' in network domain 'Enterprise%20message%20routing%20(EMR)%20Development' (data centre 'EU7').
(devdock01) Resolving target network domain 'Enterprise%20message%20routing%20(EMR)%20Development' in region 'EU'...
(devdock01) Resolving target VLAN 'Development' in network domain 'Enterprise%20message%20routing%20(EMR)%20Development'...
(devdock01) Resolving OS image 'Ubuntu 14.04 2 CPU' in data centre 'EU7'...
Creating machine...
(devdock01) Local machine's public IP address is '203.158.32.35'.
(devdock01) Importing SSH key...
(devdock01) Creating server 'devdock01'...
Wrapper Docker Machine process exiting due to closed plugin server (connection is shut down)
Error creating machine: Error in driver during machine creation: unexpected EOF</pre>

**Comment by tintoy** [comment]
Thanks! Yeah I just ran into this yesterday with some changes I was making to our Terraform driver. It's a bug in our [CloudControl client for Go](https://github.com/DimensionDataResearch/go-dd-cloud-compute/), and is being tracked [here](https://github.com/DimensionDataResearch/go-dd-cloud-compute/issues/7).

Sorry for the inconvenience, I'll update this issue when it's fixed (should be by the end of today).

**Comment by tintoy** [comment]
Fixed in [v0.2](https://github.com/DimensionDataResearch/docker-machine-driver-ddcloud/releases/tag/v0.2).

@adrianvolpe, feel free to try out the new release when you have time and let me know if you have any problems.
