### ISSUE TITLE
Add (optional) command-line argument to specify OS image name

### ISSUE THREAD

**Issue by tintoy** [DimensionDataResearch/docker-machine-driver-ddcloud#3]
For now, this will only be for OS images, not customer images (I'm unsure as to just how clever the core Docker Machine logic for installing Docker actually is, but I figure most of our OS (built-in) images are probably OK.

- [x] Implementation
- [x] Documentation

@adrianvolpe, will this be sufficient for your use case?

**Comment by adrianvolpe** [comment]
Yes that will be awesome!  The RedHat images provided by you guys is more than enough.

**Comment by tintoy** [comment]
Implemented in [v0.3](https://github.com/DimensionDataResearch/docker-machine-driver-ddcloud/releases/tag/v0.3).

Let me know if you have any problems :)
