### ISSUE TITLE
Environment variables should use MCP_ prefix instead of DD_COMPUTE_

### ISSUE THREAD

**Issue by bernard357** [DimensionDataResearch/docker-machine-driver-ddcloud#4]
This is to align with best practice on MCP documentation. By using MCP_ prefix we encourage our partners to use their Provider MCP or other forms of white-label services.

**Comment by tintoy** [comment]
Ok, that sounds pretty reasonable to me :)

**Comment by tintoy** [comment]
How about for our Terraform provider, @bernard357 - do you feel it should be changed there, too?

**Comment by tintoy** [comment]
By the way, although I'm changing the environment variables, I'm leaving the driver name as "ddcloud" for both Docker Machine and Terraform. That's probably too hard to change now, and "MCP" might be too short for a driver name (a 3-letter name is probably quite common and collisions are likely).

**Comment by bernard357** [comment]
Thanks Adam. With the separate move towards docs.mcp-services.net for the documentation, this is making an appealing value proposition to our partners. Tomorrow is the official public launch of EU9, with our partner in Belgium. Perfect timing!
